- server/schemas/typeDefs.js
Updating Number type to Int in typeDefs
> Updating Number type to Int in typeDefs

- client/src/App.js
- client/src/components/Navbar/index.js
- client/src/index.css
- client/src/index.js
- client/src/pages/Login.js
- client/src/pages/Profile.js
- client/src/pages/Signup.js
- client/src/utils/mutations.js
Finalized login page. Made changes to index.js and app.js. Also tweaked the navbar.js to set a background color.
> Js login app

- server/models/User.js
- server/schemas/resolvers.js
- server/schemas/typeDefs.js
Updated user model; user, user queries, and user mutations in typeDefs; Updated user queries and mutations in resolvers
> User model

- server/seeders/userSeeds.json
Updated user seeds to include first and last names
> Updated user seeds

- server/seeders/userSeeds.json
> Update to seeds

- client/src/App.js
- client/src/pages/Login.js
- client/src/pages/Signup.js
- client/src/utils/mutations.js
Completed signup. Tested data.
> Completed signup

- client/src/utils/mutations.js
- client/src/utils/queries.js
- server/models/Season.js
- server/models/index.js
- server/schemas/resolvers.js
- server/schemas/typeDefs.js
- server/seeders/leagueSeeds.json
- server/seeders/seasonSeeds.json
- server/seeders/seed.js
Create, read one, and read all mutations for league, season, team, and player now functional
> Muts create

- server/seeders/seasonSeeds.json
- server/seeders/seed.js
- server/seeders/soccerPlayerSeeds.json
- server/seeders/soccerTeamSeeds.json
Created seeds for League, Season, SoccerTeam, SoccerPlayer; added to seeds script
> Created seeds

- client/src/App.js
- client/src/pages/Home.js
- client/src/pages/League.js
- client/src/pages/Player.js
- client/src/pages/Team.js
Created season page and popup.
> League Season

- client/src/pages/Leagues.js
- client/src/pages/Team.js
- client/src/pages/Teams.js
Dropdowns still need styling in Teams.js. Need input on how to gather data for adding leagues and teams - will update
> Added 'Add League' and 'Add Team' forms to leagues and teams pages.

- client/src/utils/queries.js
- server/schemas/resolvers.js
- server/schemas/typeDefs.js
Query one and query all soccer games functional
> Query one and query all soccer games functional

- client/src/pages/Leagues.js
- client/src/pages/Teams.js
- client/src/utils/mutations.js
Just the buttons! No functionality yet
> Added edit and delete buttons to league and team cards.

- server/seeders/soccerGameSeeds.json
> Updating game seeds

- client/src/utils/queries.js
Updating query one soccer team
> Updating query one soccer team

- client/src/components/Forms/AddSeason.js
- client/src/components/Forms/EditTeam.js
- client/src/pages/Leagues.js
- client/src/pages/Teams.js
- client/src/utils/mutations.js
> Troubleshooting update team

- client/src/pages/Teams.js
UPDATE LEAGUES AND TEAMS WORKING
> UPDATE LEAGUES AND TEAMS WORKING

- client/src/components/Forms/EditLeague.js
- client/src/pages/Leagues.js
> Updated update mutations

- client/src/components/Forms/EditLeague.js
- client/src/pages/Leagues.js
Updated handleCloseEdit on leagues
> Updated handleCloseEdit on leagues

- client/src/pages/Leagues.js
Downloaded CH's version, deleted in finder, updated with CH's version
> Restoring Leagues.js

- client/src/App.js
- client/src/components/Forms/AddTeam.js
- client/src/index.css
- client/src/pages/Login.js
- client/src/pages/Signup.js
- server/models/User.js
- server/schemas/typeDefs.js
Added myLeagues, mySeasons, myTeams, myPlayers to User model and typeDefs. Also forcing lowercase in styling and data transfer for username in login and sign-up.
> User model update

- server/schemas/resolvers.js
> User updates
